### ISSUE TITLE
Module stopped working for ARMv6l devices

### ISSUE THREAD

**Issue by BassXX** [nigel-daniels/MMM-Weather-Now#16]
Hello,

Since last week I cannot get this Module to work anymore with my old RPi.

I get an Electron EOL Error. Is there anything that can fix this maybe? I really liked this Module. The same problem applies for MMM-3DayForecast.

Thanks and regards

**Comment by nigel-daniels** [comment]
Hi @BassXX, 

I have this running on a Pi0 W so I don't think it's the ARM architecture, although I normally develop using Docker.  

The error sounds like there is an issue with Electron. What are the versions of the OS you have, Node, Electron and MM2? If you can share any logs that show the error that would really help. 

I'll attempt to recreate the issue, if I cannot, I may need to get hold of a full Pi running electron!

**Comment by BassXX** [comment]
Hello, thanks for the answer. This is what I get upon starting up MagicMirror.


> magicmirror@2.24.0 start /home/pi/magic-mirror
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

/home/pi/magic-mirror/node_modules/electron/dist/electron exited with signal SIGILL
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror@2.24.0 start: `DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the magicmirror@2.24.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by BassXX** [comment]
@nigel-daniels I will try getting this running on a RPi 1B using docker myself.

Do you use full raspbian or lite version?

**Comment by BassXX** [comment]
Hello, I just did a full reinstall of magic mirror and now it seems to be working. no idea what was causing the problems but it works now. lets hope it stays like that :) Thanks!
