### ISSUE TITLE
Translation-Issue

### ISSUE THREAD

**Issue by Mister1Max1** [nigel-daniels/MMM-Weather-Now#17]
@nigel-daniels  It seems like a part of the information doesn´nt gets translated properly. I´ve set the langue to de (german) and one single word does get translated. But the others seems like to be dutch. It also does´nt work when I set the langue to english. Any idea hot to fix?

**Comment by nigel-daniels** [comment]
Hi @Mister1Max1, all of the language files are in the directory `./translations/`. I do not currently have a German translation set The supported files are `da, en, es, it, nb`. For this I would need a German speaker to add a file `de.json` to the `./translations/` directory. If you are able to make the translation please copy one of these files and change the display text to German then make a pull request and I can add the translation file to the set.

**Comment by Mister1Max1** [comment]
@nigel-daniels thx, I think I´m able to do that!

**Comment by nigel-daniels** [comment]
@Mister1Max1 thanks I appreciate it! Just to let you know if the words causing the problem are not in the JSON file then the cause of the problem comes from the forecast provider OpenWeather.
