### ISSUE TITLE
Wonderground version possible

### ISSUE THREAD

**Issue by c1olli** [nigel-daniels/MMM-Weather-Now#7]
Hello, 
a have a weather station and a wounderground API, but no module works with wounderground anymore.
Is it possible to get the Wounderground Versions from your MMM-Weather-Now and MMM-Weather-Forecast modules ?

**Comment by nigel-daniels** [comment]
Hi, these modules used the Weather Company API previously and now use Bit Weather. Currently there are no plans to change the API unless Bit Weather stop their free access API.  If you need to use the Wunderground API feel free to fork the project.
